---
- name: Include dynamic instances vars
  ansible.builtin.include_vars:
    file: "{{ tofu_dir }}servers.yaml"
    name: dynamic_testing_instances

- name: Add hosts to dynamic inventory
  ansible.builtin.add_host:
    name: "{{ item.name }}"
    groups:
      - "{{ item.group }}"
      - "{{ test_name }}"
    ansible_ssh_private_key_file: "{{ dynamic_testing_instances.ssh_key }}"
    ansible_ssh_host: "{{ item.fip }}"
    ansible_user: "{{ item.user }}"
    # testing_vars: "{{ item.vars }}"
  loop: "{{ dynamic_testing_instances.dynamic_instances }}"

- name: Collect facts about the new hosts
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups[test_name] }}"