---
- name: Prepare ipref instances
  ansible.builtin.include_tasks: prepare_iperf.yaml
  delegate_to: "{{ item }}"
  loop: "{{ groups[test_name] }}"

- name: Run iperf3 server
  ansible.builtin.command: iperf3 --server --daemon
  delegate_to: "{{ iperf3_srever }}"

- name: Run iperf3 client
  ansible.builtin.include_tasks: clients.yaml
  delegate_to: "{{ item }}"
  loop: "{{ groups[iperf3_clients_group] }}"

- name: Wait for iperf run to finish
  ansible.builtin.wait_for:
    timeout: 70

- name: Read and parse iperf results
  ansible.builtin.include_tasks: read_and_parse_results.yaml
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups[iperf3_clients_group] }}"

