---
- delegate_to: "{{ iperf_client }}"
  block:
  - name: Collect clients output
    ansible.builtin.slurp:
      src: /tmp/iperf3.log
    register: iperf_output

  - name: Parse iperf output
    ansible.builtin.debug:
      msg: "{{ iperf_output.content | b64decode }}"

  - name: Add results to results dict
    vars:
      dict_name: "{{ iperf_result_dict_name | default(test_name + '_iperf_results') }}"
    ansible.builtin.set_fact:
      "{{ dict_name }}": "{{ lookup('ansible.builtin.vars', dict_name) | combine({iperf_client: iperf_output.content | b64decode | from_json}) }}"
